// Auto-generated by hls_converter.py — Quantization: int8
// Composant: 1N4007
#ifndef PARAMETERS_H_
#define PARAMETERS_H_

#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>

// Précision de quantification
typedef ap_int<8> weight_t;
typedef ap_fixed<16,6> data_t;
typedef ap_fixed<16,6> accum_t;
typedef ap_fixed<16,6> result_t;

// Architecture réseau
#define N_INPUTS    1
#define N_OUTPUTS   1
#define N_LAYER_1_IN  1
#define N_LAYER_1_OUT 64
#define N_LAYER_2_IN  64
#define N_LAYER_2_OUT 128
#define N_LAYER_3_IN  128
#define N_LAYER_3_OUT 128
#define N_LAYER_4_IN  128
#define N_LAYER_4_OUT 64
#define N_LAYER_5_IN  64
#define N_LAYER_5_OUT 32
#define N_LAYER_6_IN  32
#define N_LAYER_6_OUT 1

// Paramètres SPICE encodés
#define COMPOSANT "1N4007"
#endif
